In [ ]:
#Devina Garcia 
#GIS Skills Test 

In [21]:
import os

In [22]:
os.getcwd()

'/Users/devinagarcia'

In [44]:
#Install packages
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
%matplotlib inline

In [45]:
#Download Buildings.shp 

buildings = gpd.read_file("Downloads/Buildings.shp")
buildings = buildings[['Bldg_ID','Shape_Area']]
buildings = buildings.drop(labels= range(4,8), axis=0)

#create an array of building areas for buildings A-D in order
buildings = np.array([3639.25,3594.69,3781.84,3310.95])

buildings

array([3639.25, 3594.69, 3781.84, 3310.95])

In [46]:
#Download Impervious Surfaces shapefile

imp_surfaces = gpd.read_file("Downloads/Impervious_Surface.shp")
imp_surfaces = imp_surfaces[['Shape_Area']]

#imp_surfaces will be equal to the area of it's surface
imp_surfaces = 33819.49
imp_surfaces


33819.49

In [47]:
import numpy as np

In [48]:
#create an array of the avg. monthly precipatation amounts for this area in INCHES

avgprecip = np.array([5.6,5.9,4.1,1.1,0.6,0.1,.01,.01,0.1,0.9,1.4,3.3])

#convert inches to feet by dividing by 12 inches ...
# return should avg. monthly  precip in feet 
avgprecip = avgprecip/12
avgprecip

array([0.46666667, 0.49166667, 0.34166667, 0.09166667, 0.05      ,
       0.00833333, 0.00083333, 0.00083333, 0.00833333, 0.075     ,
       0.11666667, 0.275     ])

In [49]:
# create an equation to calculate rainwater collection potential at a 85% efficiency rate for buildings A through D, and Impervious Surfaces 
# output unit should be in gallons 
# buildings = area of building (x) 
# avgprecip= avg. monthly precip amounts in ft. 
# .85 is equal to 85% collection efficiency rate
#7.48 is equal to the conversion rate of gallons per cubic foot 

#rainwater collection potential for Building A 
rainwater_collection_A = buildings[0]*avgprecip*.85*7.48

#rainwater collection potential for Building B 
rainwater_collection_B = buildings[1]*avgprecip*.85*7.48

#rainwater collection potential for Building C
rainwater_collection_C = buildings[2]*avgprecip*.85*7.48

#rainwater collection potential for Building D
rainwater_collection_D = buildings[3]*avgprecip*.85*7.48

#calculation for rainwater collection potential for impervious surface area
rainwater_collection_imp = imp_surfaces*avgprecip*.85*7.48

rainwater_collection_imp



array([100344.68146267, 105720.28939817,  73466.64178517,  19710.56243017,
        10751.215871  ,   1791.86931183,    179.18693118,    179.18693118,
         1791.86931183,  16126.8238065 ,  25086.17036567,  59131.6872905 ])

In [50]:
#Array of months in a year
months = np.array(["Jan","Feb","Mar","Apr","May","Jun","July","Aug","Sep","Oct","Nov","Dec"])

In [51]:
# 1a. Assuming an 85% collection efficiency rate, provide a table showing monthly
#rainwater collection potential for buildings A through D.

#dataFrame Table of monthly rainwater collection potential for Buildings A-D ... 
#AND for Impervious Surfaces in (gallons per cubic feet) at a 85% collection effiecency rate 


d= {'months':months, 'Bld_A':rainwater_collection_A, 'Bld_B':rainwater_collection_B,'Bld_C':rainwater_collection_C,'Bld_D':rainwater_collection_D,'Imp_Surface':rainwater_collection_imp}
pd.DataFrame(data=d)

months         Bld_A         Bld_B         Bld_C         Bld_D  \
0     Jan  10797.897367  10665.684876  11220.971403   9823.809380   
1     Feb  11376.356154  11237.060852  11822.094871  10350.084882   
2     Mar   7905.603429   7808.804998   8215.354063   7192.431867   
3     Apr   2121.015554   2095.045244   2204.119383   1929.676843   
4     May   1156.917575   1142.751951   1202.246936   1052.551005   
5     Jun    192.819596    190.458659    200.374489    175.425168   
6    July     19.281960     19.045866     20.037449     17.542517   
7     Aug     19.281960     19.045866     20.037449     17.542517   
8     Sep    192.819596    190.458659    200.374489    175.425168   
9     Oct   1735.376362   1714.127926   1803.370404   1578.826507   
10    Nov   2699.474342   2666.421219   2805.242851   2455.952345   
11    Dec   6363.046662   6285.135731   6612.358148   5789.030527   

      Imp_Surface  
0   100344.681463  
1   105720.289398  
2    73466.641785  
3    19710.562430  
4    10751.215871  
5     1791.869312  
6      179.186931  
7      179.186931  
8     1791.869312  
9    16126.823806  
10   25086.170366  
11   59131.687290

In [61]:
# b. How much precipitation could be collected from the area shown in the Impervious_Surface shapefile each year?

Imp_Surf_Collection = d['Imp_Surface'].sum()
Imp_Surf_Collection

"1b. About 414280.18 gallons of rainwater could be collected from the area shown in the Impervious Surface shapefile each year at a 85% efficency rate." 

'About 414280.18 gallons of rainwater could be collected from the area shown in the Impervious Surface shapefile each year at a 85% efficency rate.'

In [59]:
# 2. You have been asked to make a vector layer that delineates building 
#footprints and ground-level impervious surfaces for a suburban area that is 90 square miles. 
#How would you go about accomplishing this task? What data would you need?

" 2. To perform this assignment I would use the ArcGIS Pro software. In order to make a vector layer that can delineate building footprints and ground level impervious surfaces for a suburban area that is 90 square miles, I would first need to compile the most recent multispectral aerial imagery of the study site with at least four spectral bands (Red, Green, Blue, Near Infrared). I would then need the shapefile for the building footprints of the study site that will serve as a polygon feature class. I would then create a false color image of the study site using the Near Infrared - Red - Blue (RGB) combination to distinguish impervious surfaces from pervious surfaces. Under this false color composite vegetation (pervious surfaces) will appear red, while roads and roofs (impervious surfaces) will appear a grayish color. I would then overlap the building footprint polygons over the false color composite to get a more concise look of the bordering of the rooftops amongst the various land covers. I could then perform a supervised classification on the three landcovers; building footprints, impervious surfaces, and pervious surfaces. This will be done by creating training samples of each defined land cover using the overlapped false color composite. Once you train the classification machine, you will assign each land cover to a color. If you properly trained each land cover class, each land cover class will be displayed in its assigned color. Roofs, impervious surfaces, and pervious surfaces will thus be distinguished by color." 

'  To perform this assignment I would use the ArcGIS Pro software. In order to make a vector layer that can delineate building footprints and ground level impervious surfaces for a suburban area that is 90 square miles, I would first need to compile the most recent multispectral aerial imagery of the study site with at least four spectral bands (Red, Green, Blue, Near Infrared). I would then need the shapefile for the building footprints of the study site that will serve as a polygon feature class. I would then create a false color image of the study site using the Near Infrared - Red - Blue (RGB) combination to distinguish impervious surfaces from pervious surfaces. Under this false color composite vegetation (pervious surfaces) will appear red, while roads and roofs (impervious surfaces) will appear a grayish color. I would then overlap the building footprint polygons over the false color composite to get a more concise look of the bordering of the rooftops amongst the various land c